apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dp
  namespace: hnp
spec:
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
    type: RollingUpdate
  minReadySeconds: 20 # check readiness after 20 sec then continue...
  replicas: 10
  selector:
    matchLabels:
      app: item
  template:
    metadata:
      labels:
        app: item
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.2
        ports:
        - containerPort: 80
          name: http
