apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dp
  namespace: hnp
spec:
  replicas: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - item
  template:
    metadata:
      labels:
        app: item
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.2
        ports:
          - containerPort: 80