apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  namespace: hnp
spec:
  replicas: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - item
  template:
    metadata:
      labels:
        app: item
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        command: ["echo"]    # like entrypoint in docker
        args: ["Hello from pod"] # like cmd in docker
        ports:
          - containerPort: 80