apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  namespace: hnp
spec:
  replicas: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - item
  template:
    metadata:
      labels:
        app: item
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        env:
          - name: test
            value: "hi"
          - name: conf
            value: "$(test)conf1"
        ports:
          - containerPort: 80